// Rasterize Indonesia + neighbours into a pixel grid for the game map.
// Output: ../src/assets/map-data.js  (rows of chars: '.' sea, 'I' Indonesia, 'n' neighbour)
import fs from 'node:fs';
const root = new URL('../', import.meta.url);
import { feature } from 'topojson-client';
import { geoContains } from 'd3-geo';

const res = process.argv[2] || '50m';
const topo = JSON.parse(fs.readFileSync(new URL(`node_modules/world-atlas/countries-${res}.json`, root), 'utf8'));
const all = feature(topo, topo.objects.countries).features;

const W = 168, H = 64;
const LON0 = 94.5, LON1 = 141.5, LAT0 = 6.5, LAT1 = -11.5;
const dLon = (LON1 - LON0) / W, dLat = (LAT0 - LAT1) / H;

const inBox = f => {
  // quick bbox filter
  let minX = 999, maxX = -999, minY = 999, maxY = -999;
  const walk = c => (typeof c[0] === 'number'
    ? (minX = Math.min(minX, c[0]), maxX = Math.max(maxX, c[0]), minY = Math.min(minY, c[1]), maxY = Math.max(maxY, c[1]))
    : c.forEach(walk));
  walk(f.geometry?.coordinates || []);
  return maxX > LON0 && minX < LON1 && maxY > LAT1 && minY < LAT0;
};
const feats = all.filter(f => f.geometry && inBox(f));
console.error('features in box:', feats.map(f => f.properties.name).join(', '));

const SS = 4; // supersample
const rows = [];
for (let y = 0; y < H; y++) {
  let row = '';
  for (let x = 0; x < W; x++) {
    let idn = 0, nb = 0;
    for (let sy = 0; sy < SS; sy++) for (let sx = 0; sx < SS; sx++) {
      const lon = LON0 + (x + (sx + 0.5) / SS) * dLon;
      const lat = LAT0 - (y + (sy + 0.5) / SS) * dLat;
      for (const f of feats) {
        if (geoContains(f, [lon, lat])) { f.properties.name === 'Indonesia' ? idn++ : nb++; break; }
      }
    }
    const n = SS * SS, land = idn + nb;
    row += land / n >= 0.3 ? (idn >= nb ? 'I' : 'n') : '.';
  }
  rows.push(row);
}
fs.writeFileSync(new URL('src/assets/map-data.js', root),
  `// Generated by tools/rasterize-map.mjs from world-atlas (Natural Earth, public domain).\n` +
  `// ${W}x${H} px, lon ${LON0}..${LON1}, lat ${LAT0}..${LAT1}. '.' sea, 'I' Indonesia, 'n' neighbour.\n` +
  `NX.MAP = ${JSON.stringify({ W, H, LON0, LON1, LAT0, LAT1, rows }, null, 0).replace(/","/g, '",\n"')};\n`);
console.log(rows.join('\n'));
