// Rasterize a wider world map for the game (same pixel grid as map-data.js, plus a margin).
// Output: ../src/assets/map-world.js -> NX.WORLD  ('.' sea, 'I' Indonesia, 'n' neighbour)
import fs from 'node:fs';
const root = new URL('../', import.meta.url);
import { feature } from 'topojson-client';

const topo = JSON.parse(fs.readFileSync(new URL('node_modules/world-atlas/countries-50m.json', root), 'utf8'));
const all = feature(topo, topo.objects.countries).features;

// Core grid (must match map-data.js): 168x64 over lon 94.5..141.5, lat 6.5..-11.5
const dLon = 47 / 168, dLat = 18 / 64;
const MX = 24, MY = 20;                       // margin in pixels
const W = 168 + 2 * MX, H = 64 + 2 * MY;
const LON0 = 94.5 - MX * dLon, LAT0 = 6.5 + MY * dLat;

// Explode into single polygons with bounding boxes; planar point-in-polygon is plenty at this scale.
const polys = [];
for (const f of all) {
  if (!f.geometry) continue;
  const list = f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.type === 'MultiPolygon' ? f.geometry.coordinates : [];
  for (const rings of list) {
    let minX = 999, maxX = -999, minY = 999, maxY = -999;
    for (const [x, y] of rings[0]) { minX = Math.min(minX, x); maxX = Math.max(maxX, x); minY = Math.min(minY, y); maxY = Math.max(maxY, y); }
    if (maxX < LON0 - 1 || minX > LON0 + W * dLon + 1 || maxY < LAT0 - H * dLat - 1 || minY > LAT0 + 1) continue;
    polys.push({ idn: f.properties.name === 'Indonesia', rings, minX, maxX, minY, maxY });
  }
}
const inRing = (r, x, y) => { let c = false; for (let i = 0, j = r.length - 1; i < r.length; j = i++) { const [xi, yi] = r[i], [xj, yj] = r[j]; if ((yi > y) !== (yj > y) && x < (xj - xi) * (y - yi) / (yj - yi) + xi) c = !c; } return c; };
const inPoly = (p, x, y) => inRing(p.rings[0], x, y) && !p.rings.slice(1).some(h => inRing(h, x, y));

const SS = 4, rows = [];
for (let y = 0; y < H; y++) {
  let row = '';
  for (let x = 0; x < W; x++) {
    let idn = 0, nb = 0;
    for (let sy = 0; sy < SS; sy++) for (let sx = 0; sx < SS; sx++) {
      const lon = LON0 + (x + (sx + 0.5) / SS) * dLon, lat = LAT0 - (y + (sy + 0.5) / SS) * dLat;
      for (const p of polys) {
        if (lon < p.minX || lon > p.maxX || lat < p.minY || lat > p.maxY) continue;
        if (inPoly(p, lon, lat)) { p.idn ? idn++ : nb++; break; }
      }
    }
    row += (idn + nb) / (SS * SS) >= 0.3 ? (idn >= nb ? 'I' : 'n') : '.';
  }
  rows.push(row);
}
fs.writeFileSync(new URL('src/assets/map-world.js', root),
  `// Generated by tools/rasterize-world.mjs from world-atlas (Natural Earth, public domain).\n` +
  `// ${W}x${H} px. Core Indonesia box (lon 94.5..141.5, lat 6.5..-11.5) starts at pixel (${MX}, ${MY}).\n` +
  `NX.WORLD = ${JSON.stringify({ W, H, MX, MY, rows }).replace(/","/g, '",\n"')};\n`);
console.log(rows.join('\n'));
